#!/bin/sh
while true; do
    DWM_CLOCK=$( date '+%e %b %a %k:%M' );
    xsetroot -name "$DWM_CLOCK";
    sleep 1m;
done &

bgs ~/.wallpaper/calmness.png &
xrdb ~/.Xresources &
redshift &

exec awesome
