export TERM=xterm-256color
PS1='\r\n\e[1m\u\e[0m@\h \e[1m\w\e[0m\n\r\e[32m$\e[0m '

alias l='ls --literal --color=auto --group-directories-first'
alias la='l -l --human-readable --all'

alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gcm='git commit -m'
alias gd='git diff'

alias p='sudo pacaur'
alias tmux='tmux -2'
alias ta='tmux attach'
alias mkd='mkdir -pv'

# cd by directory name
shopt -s autocd
